- name: variable in ansible
  hosts: mongodb
  # This is play level variables, map
  vars:
    COURSE: DevOps
    TRAINER: Adithya
    DURATION: 120hrs
  tasks:
  - name: print hello world
    ansible.builtin.debug:
      msg: "Hello, I am learning Ansible"
  - name: print variables
    ansible.builtin.debug:
      msg: "Hello, I am learning {{COURSE}}, Trainer is {{TRAINER}}, Duration is {{DURATION}}"