- name: variables from tasks
  hosts: localost
  vars:
  -money: "50000"
   land: "100 sqft"
  tasks:
  - name: inherit the value from play
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}"
  - name: inherit the value from play and override
    vars:
    - money: "500000"
      houses: "4 houses"
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}, HOUSES: {{houses}}"


